import {useMemo,useRef,useState}from'react';
import{BarChart3,BriefcaseBusiness,Calculator,ChevronRight,Download,FileText,Info,LayoutDashboard,Plus,Printer,Save,Search,Settings2,Trash2,Upload,WalletCards,X}from'lucide-react';
import{categories,dataset,services}from'./data';import{planMetrics,serviceMetrics}from'./calculations';import type{Expense,Plan,PlanService,Service}from'./types';
const KEY='gyosei-business-planner:plans';
const yen=(n:number|null)=>n===null?'計算不能':new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
const num=(n:number)=>new Intl.NumberFormat('ja-JP').format(Math.round(n));
const uid=()=>crypto.randomUUID();
const emptyPlan=():Plan=>({id:uid(),name:'新しい事業計画',office:'',year:new Date().getFullYear(),status:'開業済み',prefecture:'',revenueTarget:10000000,profitTarget:5000000,monthlyHours:160,memo:'',services:[],expenses:[['事務所家賃',50000],['水道光熱費',10000],['通信費',8000],['行政書士会費',5000],['ソフトウェア利用料',5000],['広告費',10000]].map(([name,monthly])=>({id:uid(),name:String(name),monthly:Number(monthly),kind:'fixed'})),ownerLiving:250000,reserve:50000,taxReserve:600000,updatedAt:new Date().toISOString()});
const load=():Plan[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const tabs=[['dashboard','概要',LayoutDashboard],['services','業務を選ぶ',Search],['plan','売上計画',BriefcaseBusiness],['expenses','経費',WalletCards],['goals','目標逆算',Calculator],['settings','基本情報',Settings2]] as const;
type Tab=typeof tabs[number][0];

export default function App(){const[plans,setPlans]=useState<Plan[]>(load);const[plan,setPlan]=useState<Plan>(()=>load()[0]??emptyPlan());const[tab,setTab]=useState<Tab>('dashboard');const[toast,setToast]=useState('');const[detail,setDetail]=useState<Service|null>(null);const file=useRef<HTMLInputElement>(null);const m=useMemo(()=>planMetrics(plan),[plan]);
 const update=(patch:Partial<Plan>)=>setPlan(p=>({...p,...patch,updatedAt:new Date().toISOString()}));
 const save=()=>{const next=[plan,...plans.filter(p=>p.id!==plan.id)].slice(0,20);localStorage.setItem(KEY,JSON.stringify(next));setPlans(next);flash('計画を保存しました')};
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const exportJson=()=>{const data={schemaVersion:'1.0',appVersion:'1.0.0',exportedAt:new Date().toISOString(),businessPlan:plan,statisticDatasetVersion:dataset.datasetVersion};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`gyosei-plan-${plan.name}-${new Date().toISOString().slice(0,10).replaceAll('-','')}.json`;a.click();URL.revokeObjectURL(a.href)};
 const importJson=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||f.size>1_000_000)return flash('1MB以下のJSONを選択してください');try{const x=JSON.parse(await f.text());if(x.schemaVersion!=='1.0'||!x.businessPlan?.name||!Array.isArray(x.businessPlan.services))throw 0;setPlan({...x.businessPlan,id:uid(),updatedAt:new Date().toISOString()});setTab('dashboard');flash('計画を読み込みました')}catch{flash('対応していないJSON形式です')}e.target.value=''};
 return <div className="app"><aside><div className="brand"><div className="brandmark">行</div><div><b>GYŌSEI PLAN</b><small>事業計画シミュレーター</small></div></div><nav>{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="side-foot"><span>令和7年度 報酬額統計</span><small>データセット {dataset.datasetVersion}</small></div></aside>
 <main><header><div><p className="eyebrow">{plan.year}年度 PLAN</p><h1>{plan.name}</h1></div><div className="head-actions"><span className="saved">● ローカル保存</span><button className="iconbtn" onClick={()=>window.print()} title="印刷"><Printer size={18}/></button><button className="primary small" onClick={save}><Save size={17}/>保存</button></div></header>
 <div className="content">{tab==='dashboard'&&<Dashboard plan={plan} m={m} onMove={setTab}/>} {tab==='services'&&<ServiceSearch plan={plan} update={update} detail={setDetail}/>} {tab==='plan'&&<PlanEditor plan={plan} update={update}/>} {tab==='expenses'&&<Expenses plan={plan} update={update}/>} {tab==='goals'&&<Goals plan={plan}/>} {tab==='settings'&&<Settings plan={plan} update={update} plans={plans} setPlan={setPlan} setTab={setTab} save={save} exportJson={exportJson} file={file}/>}</div>
 <input hidden ref={file} type="file" accept="application/json,.json" onChange={importJson}/>{toast&&<div className="toast">{toast}</div>}{detail&&<Detail service={detail} selected={plan.services.some(x=>x.serviceId===detail.id)} close={()=>setDetail(null)} add={()=>{update({services:addService(plan.services,detail)});setDetail(null);flash('売上計画に追加しました')}}/>}</main></div>}

function Dashboard({plan,m,onMove}:{plan:Plan;m:ReturnType<typeof planMetrics>;onMove:(t:Tab)=>void}){const revenuePct=plan.revenueTarget?m.revenue/plan.revenueTarget*100:0,profitPct=plan.profitTarget?m.operating/plan.profitTarget*100:0;const alerts=[] as string[];if(m.revenue<plan.revenueTarget)alerts.push(`売上目標まで年間 ${yen(plan.revenueTarget-m.revenue)} 不足しています。`);if(m.hours>m.capacity)alerts.push(`年間予定作業時間が稼働可能時間を ${num(m.hours-m.capacity)}時間超過しています。`);plan.services.forEach(x=>{const s=services.find(q=>q.id===x.serviceId);if(s&&x.fee<s.average*.7)alerts.push(`${s.name}の設定報酬は統計平均より30%以上低く設定されています。`)});return <><section className="hero"><div><p className="eyebrow">BUSINESS OUTLOOK</p><h2>計画の現在地</h2><p>報酬・件数・経費から、事務所経営の見通しをリアルタイムで確認できます。</p></div><button className="primary" onClick={()=>onMove('services')}><Plus size={18}/>業務を追加</button></section><div className="kpis"><Kpi label="年間売上見込" value={yen(m.revenue)} sub={`目標達成率 ${revenuePct.toFixed(1)}%`} progress={revenuePct}/><Kpi label="年間営業利益（概算）" value={yen(m.operating)} sub={`利益目標の ${profitPct.toFixed(1)}%`} progress={profitPct}/><Kpi label="年間受任件数" value={`${num(m.cases)} 件`} sub={`必要問い合わせ ${num(m.inquiries)}件`}/><Kpi label="平均時間単価" value={m.hourly===null?'未計算':`${yen(Math.round(m.hourly))}/時`} sub={`稼働率 ${m.utilization.toFixed(1)}%`}/></div><div className="grid2"><Card title="売上目標までの進捗" action="売上計画を編集" onAction={()=>onMove('plan')}><div className="donutrow"><div className="donut" style={{'--p':`${Math.min(revenuePct,100)*3.6}deg`} as React.CSSProperties}><b>{Math.round(revenuePct)}%</b><span>達成</span></div><div className="target"><p>現在の売上見込<strong>{yen(m.revenue)}</strong></p><p>年間売上目標<strong>{yen(plan.revenueTarget)}</strong></p><p>残り<strong className="accent">{yen(Math.max(plan.revenueTarget-m.revenue,0))}</strong></p></div></div></Card><Card title="年間収支サマリー" action="経費を編集" onAction={()=>onMove('expenses')}><MetricRow label="売上" value={m.revenue} max={Math.max(m.revenue,m.fixed,1)} color="navy"/><MetricRow label="粗利益" value={m.gross} max={Math.max(m.revenue,1)} color="blue"/><MetricRow label="固定費" value={m.fixed} max={Math.max(m.revenue,1)} color="gold"/><div className="totalrow"><span>営業利益概算</span><b>{yen(m.operating)}</b></div></Card></div><div className="grid2"><Card title="業務別 売上構成">{plan.services.length?<ServiceBars plan={plan}/>:<Empty onClick={()=>onMove('services')}/>}</Card><Card title="チェックポイント"><div className="alerts">{alerts.length?alerts.slice(0,4).map((a,i)=><div key={i} className="alert"><Info size={18}/><span>{a}</span></div>):<div className="allgood">✓ 現在、重要な超過・不足はありません。</div>}</div></Card></div><div className="disclaimer"><Info size={18}/><p><b>ご利用上の注意</b><br/>本シミュレーターは将来の売上・利益を保証するものではありません。税金、社会保険、借入元金返済等は営業利益概算に含みません。</p></div></>}
function Kpi({label,value,sub,progress}:{label:string;value:string;sub:string;progress?:number}){return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{sub}</small>{progress!==undefined&&<div className="progress"><i style={{width:`${Math.min(Math.max(progress,0),100)}%`}}/></div>}</div>}
function Card({title,children,action,onAction}:{title:string;children:React.ReactNode;action?:string;onAction?:()=>void}){return <section className="card"><div className="cardhead"><h3>{title}</h3>{action&&<button onClick={onAction}>{action}<ChevronRight size={15}/></button>}</div>{children}</section>}
function MetricRow({label,value,max,color}:{label:string;value:number;max:number;color:string}){return <div className="metricrow"><div><span>{label}</span><b>{yen(value)}</b></div><i><em className={color} style={{width:`${Math.max(value/max*100,2)}%`}}/></i></div>}
function ServiceBars({plan}:{plan:Plan}){const vals=plan.services.map(x=>({x,s:services.find(q=>q.id===x.serviceId)!,v:serviceMetrics(x).revenue})),max=Math.max(...vals.map(x=>x.v),1);return <div className="servicebars">{vals.sort((a,b)=>b.v-a.v).map(({x,s,v})=><div key={x.id}><span title={s.name}>{s.name}</span><i><em style={{width:`${v/max*100}%`}}/></i><b>{yen(v)}</b></div>)}</div>}
function Empty({onClick}:{onClick:()=>void}){return <div className="empty"><BarChart3 size={34}/><p>業務を追加すると、構成比が表示されます。</p><button onClick={onClick}>業務を選ぶ</button></div>}

function ServiceSearch({plan,update,detail}:{plan:Plan;update:(p:Partial<Plan>)=>void;detail:(s:Service)=>void}){const[q,setQ]=useState('');const[cat,setCat]=useState('すべて');const filtered=services.filter(s=>(cat==='すべて'||s.category===cat)&&(`${s.name}${s.category}`.includes(q)));return <><PageTitle title="業務を選ぶ" desc="報酬額統計を参考に、取り扱う業務を売上計画へ追加します。"/><div className="filters"><label className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="業務名・カテゴリーで検索"/></label><select value={cat} onChange={e=>setCat(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><span>{filtered.length}件</span></div><div className="notice"><Info size={18}/><span>掲載金額は全国調査の統計値であり、報酬額の基準・上限・下限を示すものではありません。</span></div><div className="servicegrid">{filtered.map(s=>{const selected=plan.services.some(x=>x.serviceId===s.id);return <article className="servicecard" key={s.id}><div className="servicehead"><span className="tag">{s.category}</span><span className={`reliability r${reliability(s.respondents)}`}>参考度 {reliability(s.respondents)}</span></div><h3>{s.name}</h3><small>統計番号 {s.officialNumber} ・ 回答者 {num(s.respondents)}名</small><div className="statmain"><span>平均額<strong>{yen(s.average)}</strong></span><span>最頻値<strong>{yen(s.mode)}</strong></span></div><div className="statsmall"><span>最小 {yen(s.min)}</span><span>最大 {yen(s.max)}</span>{s.median&&<span>推定中央値 {yen(s.median)}</span>}</div><div className="cardactions"><button onClick={()=>detail(s)}>詳細を見る</button><button className={selected?'added':'primary'} disabled={selected} onClick={()=>update({services:addService(plan.services,s)})}>{selected?'追加済み':<><Plus size={16}/>計画へ追加</>}</button></div></article>})}</div></>}
const reliability=(n:number)=>n>=300?'高':n>=100?'中':n>=30?'やや低い':'低';
const addService=(current:PlanService[],s:Service):PlanService[]=>current.some(x=>x.serviceId===s.id)?current:[...current,{id:uid(),serviceId:s.id,fee:s.mode||s.average,cases:12,cost:0,hours:5,conversion:30,inquiryRate:0,ads:0,priority:'中',recurring:false,memo:''}];
function Detail({service,selected,close,add}:{service:Service;selected:boolean;close:()=>void;add:()=>void}){const max=Math.max(...service.bands.map(x=>x.rate));return <div className="modalback" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modalx" onClick={close}><X/></button><span className="tag">{service.category}</span><h2>{service.name}</h2><p>統計番号 {service.officialNumber} ・ 回答者 {num(service.respondents)}名 ・ 参考度 {reliability(service.respondents)}</p><div className="detailstats"><Kpi label="平均額" value={yen(service.average)} sub="税込・立替金除く"/><Kpi label="最頻値" value={yen(service.mode)} sub="最も回答が多い金額"/><Kpi label="推定中央値" value={service.median?yen(service.median):'未掲載'} sub="金額帯から算出"/></div><h3>金額帯別の回答割合</h3><div className="bands">{service.bands.map(b=><div key={b.label}><span>{b.label}</span><i><em style={{width:`${b.rate/max*100}%`}}/></i><b>{b.rate}%</b></div>)}</div><div className="modalnote">正確な中央値は公式資料に明記されていません。「推定中央値」は金額帯別分布から算出した参考値です。</div><div className="modalfoot"><a href={dataset.sourceUrl} target="_blank" rel="noreferrer">出典を確認</a><button className="primary" disabled={selected} onClick={add}>{selected?'追加済み':'計画へ追加'}</button></div></div></div>}

function PlanEditor({plan,update}:{plan:Plan;update:(p:Partial<Plan>)=>void}){const set=(id:string,p:Partial<PlanService>)=>update({services:plan.services.map(s=>s.id===id?{...s,...p}:s)});return <><PageTitle title="売上計画" desc="自事務所の報酬・目標件数・作業時間を設定します。" action={<span className="summarypill">{plan.services.length}業務 ・ 年間売上 {yen(planMetrics(plan).revenue)}</span>}/>{!plan.services.length?<Empty onClick={()=>{}}/>:<div className="planlist">{plan.services.map(x=>{const s=services.find(q=>q.id===x.serviceId)!;const r=serviceMetrics(x);return <article className="planrow" key={x.id}><div className="plantitle"><div><span className="tag">{s.category}</span><h3>{s.name}</h3><small>統計平均 {yen(s.average)} / 最頻値 {yen(s.mode)}</small></div><button className="trash" onClick={()=>confirm('この業務を計画から削除しますか？')&&update({services:plan.services.filter(q=>q.id!==x.id)})}><Trash2 size={17}/></button></div><div className="quick"><span>報酬額の入力補助</span><button onClick={()=>set(x.id,{fee:s.average})}>平均額</button><button onClick={()=>set(x.id,{fee:s.mode})}>最頻値</button>{s.median&&<button onClick={()=>set(x.id,{fee:s.median})}>推定中央値</button>}</div><div className="formgrid four"><Field label="自事務所報酬額（円）"><NumberInput value={x.fee} onChange={fee=>set(x.id,{fee})}/></Field><Field label="年間受任目標（件）"><NumberInput value={x.cases} onChange={cases=>set(x.id,{cases})}/></Field><Field label="変動原価／件（円）"><NumberInput value={x.cost} onChange={cost=>set(x.id,{cost})}/></Field><Field label="作業時間／件（時間）"><NumberInput value={x.hours} onChange={hours=>set(x.id,{hours})}/></Field><Field label="成約率（%）"><NumberInput value={x.conversion} onChange={conversion=>set(x.id,{conversion})} max={100}/></Field><Field label="問い合わせ率（%）"><NumberInput value={x.inquiryRate} onChange={inquiryRate=>set(x.id,{inquiryRate})} max={100}/></Field><Field label="年間広告費配賦（円）"><NumberInput value={x.ads} onChange={ads=>set(x.id,{ads})}/></Field><Field label="優先度"><select value={x.priority} onChange={e=>set(x.id,{priority:e.target.value as PlanService['priority']})}><option>高</option><option>中</option><option>低</option></select></Field></div><div className="rowmetrics"><span>年間売上<b>{yen(r.revenue)}</b></span><span>粗利益<b>{yen(r.gross)}</b></span><span>粗利益率<b>{r.margin.toFixed(1)}%</b></span><span>時間単価<b>{r.hourly===null?'計算不能':yen(Math.round(r.hourly))}</b></span><span>必要問い合わせ<b>{r.inquiries===null?'計算不能':`${r.inquiries}件`}</b></span></div></article>})}</div>}</>}

function Expenses({plan,update}:{plan:Plan;update:(p:Partial<Plan>)=>void}){const set=(id:string,p:Partial<Expense>)=>update({expenses:plan.expenses.map(e=>e.id===id?{...e,...p}:e)});const m=planMetrics(plan);return <><PageTitle title="経費計画" desc="固定費と、事業主として確保したい金額を分けて設定します。"/><div className="gridform"><Card title="固定費（月額）"><div className="expensehead"><span>経費名</span><span>月額</span><span>年額</span><span></span></div>{plan.expenses.map(e=><div className="expenserow" key={e.id}><input value={e.name} maxLength={200} onChange={x=>set(e.id,{name:x.target.value})}/><NumberInput value={e.monthly} onChange={monthly=>set(e.id,{monthly})}/><b>{yen(e.monthly*12)}</b><button className="trash" onClick={()=>update({expenses:plan.expenses.filter(x=>x.id!==e.id)})}><Trash2 size={16}/></button></div>)}<button className="addline" onClick={()=>update({expenses:[...plan.expenses,{id:uid(),name:'新しい経費',monthly:0,kind:'fixed'}]})}><Plus size={16}/>経費を追加</button><div className="totalrow"><span>年間固定費 合計</span><b>{yen(m.fixed)}</b></div></Card><Card title="事業主必要額（経費外）"><p className="muted">生活費等は会計上の経費と分け、参考損益分岐点にのみ反映します。</p><Field label="毎月確保したい生活費（円）"><NumberInput value={plan.ownerLiving} onChange={ownerLiving=>update({ownerLiving})}/></Field><Field label="毎月確保したい内部留保（円）"><NumberInput value={plan.reserve} onChange={reserve=>update({reserve})}/></Field><Field label="年間納税準備額（円）"><NumberInput value={plan.taxReserve} onChange={taxReserve=>update({taxReserve})}/></Field><div className="summarybox"><span>損益分岐点売上<b>{yen(m.breakEven)}</b></span><span>生活費等を含む必要売上参考値<b>{yen(m.referenceBreakEven)}</b></span><span>年間余剰<b className={m.surplus<0?'negative':''}>{yen(m.surplus)}</b></span></div></Card></div></>}

function Goals({plan}:{plan:Plan}){const[method,setMethod]=useState<'one'|'ratio'|'profit'>('one');const[chosen,setChosen]=useState(plan.services[0]?.id||'');const m=planMetrics(plan),short=Math.max(plan.revenueTarget-m.revenue,0);let rows:{name:string;cases:number;revenue:number;gross:number;hours:number;inquiries:number|null}[]=[];if(short&&plan.services.length){let targets=[...plan.services];if(method==='one')targets=targets.filter(x=>x.id===chosen);if(method==='profit')targets.sort((a,b)=>(serviceMetrics(b).hourly??0)-(serviceMetrics(a).hourly??0)).splice(1);if(method==='ratio'){const total=targets.reduce((n,x)=>n+x.cases,0)||targets.length;rows=targets.map(x=>{const share=x.cases?x.cases/total:1/targets.length;return goalRow(x,short*share)});}else if(targets[0])rows=[goalRow(targets[0],short)]}const totalHours=rows.reduce((n,r)=>n+r.hours,0);return <><PageTitle title="目標逆算" desc="現在の計画と目標の差から、追加で必要な件数と行動量を試算します。"/><div className="goalhero"><span>売上目標までの不足額</span><strong>{yen(short)}</strong><small>目標 {yen(plan.revenueTarget)} − 現在 {yen(m.revenue)}</small></div><Card title="増やし方を選択"><div className="methods"><label><input type="radio" checked={method==='one'} onChange={()=>setMethod('one')}/><span><b>1業務で補う</b><small>選択した業務だけで不足売上を補います</small></span></label><label><input type="radio" checked={method==='ratio'} onChange={()=>setMethod('ratio')}/><span><b>現在の比率で増やす</b><small>全業務の件数比率に応じて配分します</small></span></label><label><input type="radio" checked={method==='profit'} onChange={()=>setMethod('profit')}/><span><b>時間単価を優先</b><small>粗利益時間単価が最も高い業務を増やします</small></span></label></div>{method==='one'&&<Field label="優先して増やす業務"><select value={chosen} onChange={e=>setChosen(e.target.value)}>{plan.services.map(x=><option value={x.id} key={x.id}>{services.find(s=>s.id===x.serviceId)?.name}</option>)}</select></Field>}</Card><Card title="逆算結果">{!plan.services?<p className="muted">先に売上計画へ業務を追加してください。</p>:short===0?<div className="allgood">✓ 現在の計画で売上目標を達成しています。</div>:<><div className="resulttable"><div><b>業務</b><b>追加件数</b><b>追加売上</b><b>追加粗利益</b><b>追加時間</b><b>追加問合せ</b></div>{rows.map(r=><div key={r.name}><span>{r.name}</span><strong>+{r.cases}件</strong><span>{yen(r.revenue)}</span><span>{yen(r.gross)}</span><span>{num(r.hours)}h</span><span>{r.inquiries===null?'計算不能':`${r.inquiries}件`}</span></div>)}</div>{m.hours+totalHours>m.capacity&&<div className="warning">年間稼働可能時間を {num(m.hours+totalHours-m.capacity)}時間超過する試算です。</div>}</>}</Card></>}
function goalRow(x:PlanService,amount:number){const count=Math.ceil(amount/x.fee),s=services.find(q=>q.id===x.serviceId)!;return{name:s.name,cases:count,revenue:count*x.fee,gross:count*(x.fee-x.cost),hours:count*x.hours,inquiries:x.conversion?Math.ceil(count/(x.conversion/100)):null}}

function Settings({plan,update,plans,setPlan,setTab,save,exportJson,file}:{plan:Plan;update:(p:Partial<Plan>)=>void;plans:Plan[];setPlan:(p:Plan)=>void;setTab:(t:Tab)=>void;save:()=>void;exportJson:()=>void;file:React.RefObject<HTMLInputElement|null>}){return <><PageTitle title="基本情報・保存" desc="計画の前提を設定し、バックアップや別シナリオを管理します。"/><div className="gridform"><Card title="計画の基本情報"><div className="formgrid"><Field label="計画名（必須）"><input value={plan.name} maxLength={200} onChange={e=>update({name:e.target.value})}/></Field><Field label="事務所名"><input value={plan.office} maxLength={200} onChange={e=>update({office:e.target.value})}/></Field><Field label="計画年度"><NumberInput value={plan.year} onChange={year=>update({year})}/></Field><Field label="開業状況"><select value={plan.status} onChange={e=>update({status:e.target.value})}><option>開業予定</option><option>開業1年未満</option><option>開業1年以上3年未満</option><option>開業3年以上5年未満</option><option>開業5年以上</option><option>行政書士法人</option></select></Field><Field label="年間売上目標（円）"><NumberInput value={plan.revenueTarget} onChange={revenueTarget=>update({revenueTarget})}/></Field><Field label="年間利益目標（円）"><NumberInput value={plan.profitTarget} onChange={profitTarget=>update({profitTarget})}/></Field><Field label="月間稼働可能時間"><NumberInput value={plan.monthlyHours} onChange={monthlyHours=>update({monthlyHours})}/></Field><Field label="メモ"><textarea value={plan.memo} maxLength={2000} onChange={e=>update({memo:e.target.value})}/></Field></div><button className="primary" onClick={save}><Save size={17}/>この計画を保存</button></Card><Card title="保存・バックアップ"><div className="fileactions"><button onClick={exportJson}><Download/>JSONを書き出す<small>現在の計画をバックアップ</small></button><button onClick={()=>file.current?.click()}><Upload/>JSONを読み込む<small>保存済みデータを復元</small></button><button onClick={()=>window.print()}><Printer/>計画書を印刷<small>ブラウザからPDF保存も可能</small></button><button onClick={()=>{setPlan(emptyPlan());setTab('settings')}}><FileText/>新しい計画<small>別シナリオを作成</small></button></div><h3 className="subhead">保存済み計画</h3>{plans.length?<div className="savedplans">{plans.map(p=><button key={p.id} onClick={()=>{setPlan(p);setTab('dashboard')}}><span><b>{p.name}</b><small>{new Date(p.updatedAt).toLocaleString('ja-JP')}</small></span><ChevronRight/></button>)}</div>:<p className="muted">保存済みの計画はありません。</p>}</Card></div><Source/></>}
function Source(){return <section className="source"><h3>データ出典と免責事項</h3><p>出典：{dataset.sourceOrganization}「{dataset.surveyName}」／調査年度 {dataset.surveyYear}年／金額は税込・立替金を除く。</p><p>掲載金額は全国調査の統計値であり、報酬額の基準・上限・下限を示すものではありません。同一業務でも具体的な内容、地域、難易度、実費、追加対応等により報酬額は異なります。自事務所の報酬額は各自の責任で設定してください。</p><a href={dataset.sourceUrl} target="_blank" rel="noreferrer">公式資料を確認する</a></section>}
function PageTitle({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}){return <div className="pagetitle"><div><h2>{title}</h2><p>{desc}</p></div>{action}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function NumberInput({value,onChange,max=999999999}:{value:number;onChange:(n:number)=>void;max?:number}){return <input type="number" min="0" max={max} value={value} onChange={e=>onChange(Math.min(max,Math.max(0,Number(e.target.value)||0)))}/>}
